version: "3.9"
services:
  db:
    container_name: db-LCW.STORE  
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_DATABASE: LCW.STORE_db 
      MYSQL_USER: LCW 
      MYSQL_PASSWORD: 123456
    networks:
      - net-LCW 
  web:
    container_name: web-LCW 
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-LCW
networks:
  net-LCW:

    
